spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yandex_api
    username: paincake
    password: biliberda9999
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
